version: "3.9"

services:
  auth-service:
    build: .
    container_name: auth-service
    restart: always
    command: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - ecommerce-network

  auth-worker:
    build: .
    container_name: sms-whatsapp-worker
    restart: always
    command: ./worker
    env_file:
      - .env
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    external: true